#!/bin/bash

# Assumes a script colocated in the same directory called dt-chef-solo.py


PYEXE="python"
EZEXE="easy_install"

# DL: leaving this around as we may need same tricks for OOI centOS6 image

# hack for OOI base image which doesn't have easy_install-2.5 in $PATH
# where this script runs.
#if [ -d /opt/python2.5/bin ]; then
#    PATH="$PATH:/opt/python2.5/bin"
#fi

#PYTHON1="python2.5"
#EZ1="easy_install-2.5"
#PYTHON2="python2.6"
#EZ2="easy_install-2.6"

#$PYTHON1 -c "import os"
#if [ $? -eq 0 ]; then
#    PYEXE=$PYTHON1
#    EZEXE=$EZ1
#else
#    $PYTHON2 -c "import os"
#    if [ $? -eq 0 ]; then
#        PYEXE=$PYTHON2
#        EZEXE=$EZ2
#    else
#        echo "Could not locate a working Python installation"
#        exit 1
#    fi
#fi

$PYEXE -c "import simplejson"
if [ $? -ne 0 ]; then
    echo "installing simplejson"
    $EZEXE simplejson
    if [ $? -ne 0 ]; then
        echo "failed to install simplejson for $PYEXE"
        exit 1
    fi
    
    # doublecheck
    $PYEXE -c "import simplejson"
    if [ $? -ne 0 ]; then
        echo "failed to install simplejson for $PYEXE"
        exit 1
    fi
    
else
    echo "simplejson existed for $PYEXE"
fi

dir=`dirname $0`
$PYEXE $dir/dt-chef-solo.py $1 &> /opt/dt-chef-solo.log
CHEF_EXIT=$?

# If Chef failed, output the end of the Chef log
if [ $CHEF_EXIT != 0 ]; then
  tail -100 /opt/dt-chef-solo.log
fi
exit $CHEF_EXIT
